//
//  words.swift
//  hangman
//
//  Created by Lalana Thanthirigama on 2024-10-14.
//

let sevenLetterWords = [
    "ACCOUNT", "ADVISER", "AIRPORT", "ALCOHOL", "AMATEUR", "ANALYST", "ANXIETY", "APOLOGY", "APPOINT", "ARRANGE",
    "ARTICLE", "ATTEMPT", "BALANCE", "BATTERY", "BLANKET", "BROTHER", "CABINET", "CAPITAL", "CAPTAIN", "CEILING",
    "CENTRAL", "CHAMBER", "CHARITY", "CHICKEN", "CLARITY", "CLIMATE", "COLLEGE", "COMMENT", "COMPLEX", "CONCEPT",
    "CONCERN", "CONNECT", "CONTACT", "CONTEXT", "CONVERT", "COUNCIL", "COUNTRY", "CULTURE", "CURRENT", "CUSTODY",
    "DECLINE", "DEFAULT", "DEFENSE", "DENSITY", "DEPOSIT", "DESERVE", "DESTROY", "DIGITAL", "DISEASE", "DISMISS",
    "DISPUTE", "DISPLAY", "DIVERSE", "DYNAMIC", "ECONOMY", "ELEMENT", "EMBRACE", "EMINENT", "EMOTION", "ENDORSE",
    "ENHANCE", "EPISODE", "ETERNAL", "EXECUTE", "FACULTY", "FICTION", "FINANCE", "FIREMAN", "FITNESS", "FORTUNE",
    "FREIGHT", "GENERAL", "GENUINE", "GRAPHIC", "HARMONY", "HARVEST", "HISTORY", "HOLIDAY", "HONESTY", "HORIZON",
    "ILLEGAL", "IMAGINE", "IMPRESS", "IMPROVE", "INQUIRY", "INSPIRE", "INSTALL", "JOURNAL", "JUSTICE", "KITCHEN",
    "LIBERAL", "LIBRARY", "LOYALTY", "MANAGER", "MEASURE", "MISSION", "MYSTERY", "NUCLEAR", "OFFENSE", "PASSAGE",
    "PATRIOT", "PHYSICS", "POPULAR", "PRECISE", "PREMIUM", "PROMISE", "PURPOSE", "QUALITY", "REBUILD", "REFORM"
]
